import {
  ArticleFeedItem,
  Cluster,
  DashboardResponse,
  Entity,
  PredictionAnalyticsResponse,
  ScheduleRace,
  SessionResult,
  Source,
  StandingEntry,
  TeamCarWatch,
  TimelinePhase,
  CompletedWeekendResult,
} from "@/lib/types";

const sources: Source[] = [
  {
    id: "source_formula1",
    name: "Formula1.com",
    kind: "official",
    reliability_tier: "anchor",
    base_url: "https://www.formula1.com",
  },
  {
    id: "source_fia",
    name: "FIA",
    kind: "official",
    reliability_tier: "anchor",
    base_url: "https://www.fia.com",
  },
  {
    id: "source_mercedes",
    name: "Mercedes",
    kind: "team",
    reliability_tier: "primary",
    base_url: "https://www.mercedesamgf1.com",
  },
  {
    id: "source_the_race",
    name: "The Race",
    kind: "media",
    reliability_tier: "context",
    base_url: "https://www.the-race.com",
  },
];

const entities: Entity[] = [
  { id: "team_mercedes", name: "Mercedes", kind: "team", slug: "mercedes" },
  { id: "team_ferrari", name: "Ferrari", kind: "team", slug: "ferrari" },
  { id: "team_mclaren", name: "McLaren", kind: "team", slug: "mclaren" },
  { id: "driver_antonelli", name: "Kimi Antonelli", kind: "driver", slug: "kimi-antonelli" },
  { id: "driver_russell", name: "George Russell", kind: "driver", slug: "george-russell" },
  { id: "driver_leclerc", name: "Charles Leclerc", kind: "driver", slug: "charles-leclerc" },
  { id: "driver_piastri", name: "Oscar Piastri", kind: "driver", slug: "oscar-piastri" },
  { id: "circuit_miami", name: "Miami International Autodrome", kind: "circuit", slug: "miami" },
];

const timeline: TimelinePhase[] = [
  {
    phase: "between_races",
    state: "active",
    headline: "Japan is complete and the season has shifted into a between-races reset before Miami.",
    focus: "standings, schedule, next-race framing",
  },
  {
    phase: "pre_race",
    state: "upcoming",
    headline: "Miami build-up centers on whether anyone can break Mercedes' opening run.",
    focus: "championship pressure, sprint format, setup direction",
  },
  {
    phase: "practice",
    state: "upcoming",
    headline: "There is only one proper practice hour in Miami before sprint qualifying.",
    focus: "single-session learning, track evolution, compromise",
  },
  {
    phase: "sprint_qualifying",
    state: "upcoming",
    headline: "Sprint qualifying will set the tone for the compressed weekend.",
    focus: "track position, tire prep, lap execution",
  },
  {
    phase: "race",
    state: "upcoming",
    headline: "The race will test whether Antonelli can extend his championship lead.",
    focus: "degradation, safety car timing, conversion of pace",
  },
];

function byId<T extends { id: string }>(items: T[], ids: string[]): T[] {
  return ids.map((id) => items.find((item) => item.id === id)).filter(Boolean) as T[];
}

const driverStandings: StandingEntry[] = [
  { position: 1, name: "Kimi Antonelli", code: "ANT", team: "Mercedes", nationality: "ITA", points: 72 },
  { position: 2, name: "George Russell", code: "RUS", team: "Mercedes", nationality: "GBR", points: 63 },
  { position: 3, name: "Charles Leclerc", code: "LEC", team: "Ferrari", nationality: "MON", points: 49 },
  { position: 4, name: "Lewis Hamilton", code: "HAM", team: "Ferrari", nationality: "GBR", points: 41 },
  { position: 5, name: "Lando Norris", code: "NOR", team: "McLaren", nationality: "GBR", points: 25 },
  { position: 6, name: "Oscar Piastri", code: "PIA", team: "McLaren", nationality: "AUS", points: 21 },
  { position: 7, name: "Oliver Bearman", code: "BEA", team: "Haas F1 Team", nationality: "GBR", points: 17 },
  { position: 8, name: "Pierre Gasly", code: "GAS", team: "Alpine", nationality: "FRA", points: 15 },
  { position: 9, name: "Max Verstappen", code: "VER", team: "Red Bull Racing", nationality: "NED", points: 12 },
  { position: 10, name: "Liam Lawson", code: "LAW", team: "Racing Bulls", nationality: "NZL", points: 10 },
];

const constructorStandings: StandingEntry[] = [
  { position: 1, name: "Mercedes", points: 135 },
  { position: 2, name: "Ferrari", points: 90 },
  { position: 3, name: "McLaren", points: 46 },
  { position: 4, name: "Haas F1 Team", points: 18 },
  { position: 5, name: "Alpine", points: 16 },
  { position: 6, name: "Red Bull Racing", points: 16 },
  { position: 7, name: "Racing Bulls", points: 14 },
  { position: 8, name: "Audi", points: 2 },
  { position: 9, name: "Williams", points: 2 },
  { position: 10, name: "Cadillac", points: 0 },
  { position: 11, name: "Aston Martin", points: 0 },
];

const teamCars: TeamCarWatch[] = [
  {
    team: "Mercedes",
    points: 135,
    championship_position: 1,
    drivers: [
      { name: "Kimi Antonelli", code: "ANT", points: 72, position: 1 },
      { name: "George Russell", code: "RUS", points: 63, position: 2 },
    ],
    update_status: "No confirmed technical update surfaced in the current feed, but Mercedes remains the pace benchmark.",
  },
  {
    team: "Ferrari",
    points: 90,
    championship_position: 2,
    drivers: [
      { name: "Charles Leclerc", code: "LEC", points: 49, position: 3 },
      { name: "Lewis Hamilton", code: "HAM", points: 41, position: 4 },
    ],
    update_status: "Ferrari remains the clearest challenger in the current feed, though no new official upgrade note is attached here.",
  },
  {
    team: "McLaren",
    points: 46,
    championship_position: 3,
    drivers: [
      { name: "Lando Norris", code: "NOR", points: 25, position: 5 },
      { name: "Oscar Piastri", code: "PIA", points: 21, position: 6 },
    ],
    update_status: "McLaren's car still reads as the strongest non-Mercedes race challenger in the current feed.",
  },
];

const articleFeed: ArticleFeedItem[] = [
  {
    id: "doc_miami_schedule",
    title: "2026 Miami Grand Prix schedule",
    url: "https://www.formula1.com/en/racing/2026/miami",
    publish_time: "2026-04-01T17:00:00Z",
    kind: "schedule",
    stance: "official",
    source_name: "Formula1.com",
    source_kind: "official",
  },
  {
    id: "doc_driver_standings",
    title: "2026 Drivers' Standings",
    url: "https://www.formula1.com/en/results/2026/drivers",
    publish_time: "2026-04-01T18:00:00Z",
    kind: "standings",
    stance: "official",
    source_name: "Formula1.com",
    source_kind: "official",
  },
  {
    id: "doc_team_standings",
    title: "2026 Teams' Standings",
    url: "https://www.formula1.com/en/results/2026/team",
    publish_time: "2026-04-01T18:00:00Z",
    kind: "standings",
    stance: "official",
    source_name: "Formula1.com",
    source_kind: "official",
  },
  {
    id: "doc_miami_prediction_basis",
    title: "Why Miami could reward the strongest all-round car again",
    url: "https://www.the-race.com/formula-1/miami-2026-form-guide",
    publish_time: "2026-04-01T19:30:00Z",
    kind: "analysis_article",
    stance: "analysis",
    source_name: "The Race",
    source_kind: "media",
  },
];

const performanceCharts = {
  race_labels: ["Australia", "China", "Japan"],
  contenders: driverStandings.slice(0, 10).map((entry) => entry.name),
  points_series: [
    { label: "Kimi Antonelli", values: [18, 25, 25] },
    { label: "George Russell", values: [25, 20, 12] },
    { label: "Charles Leclerc", values: [15, 19, 15] },
    { label: "Lewis Hamilton", values: [12, 17, 12] },
    { label: "Lando Norris", values: [10, 5, 10] },
    { label: "Oscar Piastri", values: [8, 3, 18] },
    { label: "Oliver Bearman", values: [6, 6, 5] },
    { label: "Pierre Gasly", values: [4, 8, 3] },
    { label: "Max Verstappen", values: [2, 6, 4] },
    { label: "Liam Lawson", values: [1, 7, 2] },
  ],
  speed_series: [
    { label: "Kimi Antonelli", values: [322, 329, 318] },
    { label: "George Russell", values: [320, 327, 317] },
    { label: "Charles Leclerc", values: [319, 325, 315] },
    { label: "Lewis Hamilton", values: [318, 324, 314] },
    { label: "Lando Norris", values: [321, 326, 316] },
    { label: "Oscar Piastri", values: [320, 325, 316] },
    { label: "Oliver Bearman", values: [316, 320, 311] },
    { label: "Pierre Gasly", values: [315, 319, 309] },
    { label: "Max Verstappen", values: [323, 328, 317] },
    { label: "Liam Lawson", values: [317, 321, 312] },
  ],
  fastest_lap_series: [
    { label: "Kimi Antonelli", values: [91.842, 88.511, 89.362] },
    { label: "George Russell", values: [91.955, 88.744, 89.616] },
    { label: "Charles Leclerc", values: [92.114, 89.103, 90.229] },
    { label: "Lewis Hamilton", values: [92.307, 89.241, 90.383] },
    { label: "Lando Norris", values: [92.004, 88.993, 89.944] },
    { label: "Oscar Piastri", values: [92.120, 88.901, 90.364] },
    { label: "Oliver Bearman", values: [92.664, 89.821, 91.102] },
    { label: "Pierre Gasly", values: [92.783, 89.934, 91.286] },
    { label: "Max Verstappen", values: [91.910, 89.002, 90.417] },
    { label: "Liam Lawson", values: [92.541, 89.711, 91.048] },
  ],
};

const australiaWeekendSessions: SessionResult[] = [
  {
    name: "Practice 1",
    category: "practice",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/Australia.html",
    entries: [
      { position: 1, driver: "George Russell", team: "Mercedes", metric: "1:18.441" },
      { position: 2, driver: "Charles Leclerc", team: "Ferrari", metric: "+0.084s" },
      { position: 3, driver: "Lando Norris", team: "McLaren", metric: "+0.143s" },
    ],
  },
  {
    name: "Qualifying",
    category: "qualifying",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/Australia.html",
    entries: [
      { position: 1, driver: "George Russell", team: "Mercedes", metric: "1:16.982" },
      { position: 2, driver: "Kimi Antonelli", team: "Mercedes", metric: "+0.119s" },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", metric: "+0.247s" },
    ],
  },
  {
    name: "Race",
    category: "race",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/Australia.html",
    entries: [
      { position: 1, driver: "George Russell", team: "Mercedes", metric: "1:31:17.204", points: 25 },
      { position: 2, driver: "Kimi Antonelli", team: "Mercedes", metric: "+4.281s", points: 18 },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", metric: "+9.607s", points: 15 },
    ],
  },
];

const chinaWeekendSessions: SessionResult[] = [
  {
    name: "Sprint",
    category: "race",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/China.html",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "30:42.118", points: 8 },
      { position: 2, driver: "Liam Lawson", team: "Racing Bulls", metric: "+2.194s", points: 7 },
      { position: 3, driver: "George Russell", team: "Mercedes", metric: "+3.020s", points: 6 },
    ],
  },
  {
    name: "Qualifying",
    category: "qualifying",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/China.html",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "1:30.881" },
      { position: 2, driver: "Max Verstappen", team: "Red Bull Racing", metric: "+0.101s" },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", metric: "+0.189s" },
    ],
  },
  {
    name: "Race",
    category: "race",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/China.html",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "1:33:54.903", points: 25 },
      { position: 2, driver: "Charles Leclerc", team: "Ferrari", metric: "+6.221s", points: 18 },
      { position: 3, driver: "Lewis Hamilton", team: "Ferrari", metric: "+9.018s", points: 15 },
    ],
  },
];

const latestWeekendSessions: SessionResult[] = [
  {
    name: "Practice 1",
    category: "practice",
    status: "completed",
    source_url: "https://www.formula1.com/en/latest/article/fp1-russell-heads-mercedes-1-2-in-opening-practice-session-for-japanese.1WB5ian2z0xW2JirY293oM",
    entries: [
      { position: 1, driver: "George Russell", team: "Mercedes", metric: "1:31.666" },
      { position: 2, driver: "Kimi Antonelli", team: "Mercedes", metric: "+0.026s" },
      { position: 3, driver: "Lando Norris", team: "McLaren", metric: "+0.132s" },
    ],
  },
  {
    name: "Practice 2",
    category: "practice",
    status: "completed",
    source_url: "https://www.formula1.com/en/racing/2026/Japan.html",
    entries: [
      { position: 1, driver: "Oscar Piastri", team: "McLaren", metric: "1:30.133" },
      { position: 2, driver: "Kimi Antonelli", team: "Mercedes", metric: "+0.092s" },
      { position: 3, driver: "George Russell", team: "Mercedes", metric: "+0.205s" },
    ],
  },
  {
    name: "Practice 3",
    category: "practice",
    status: "completed",
    source_url: "https://www.formula1.com/en/latest/article/fp3-antonelli-beats-mercedes-team-mate-russell-to-fastest-time-in-final.NfWBOJEAaBCzWLWBDz81J/",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "1:29.362" },
      { position: 2, driver: "George Russell", team: "Mercedes", metric: "+0.254s" },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", metric: "+0.867s" },
    ],
  },
  {
    name: "Qualifying",
    category: "qualifying",
    status: "completed",
    source_url: "https://www.formula1.com/en/results.html/2026/races/1281/japan/starting-grid.html",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "1:28.778" },
      { position: 2, driver: "George Russell", team: "Mercedes", metric: "1:29.076" },
      { position: 3, driver: "Oscar Piastri", team: "McLaren", metric: "1:29.132" },
    ],
  },
  {
    name: "Race",
    category: "race",
    status: "completed",
    source_url: "https://www.formula1.com/en/results/2026/races/1281/japan/race-result",
    entries: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes", metric: "1:28:03.403", points: 25 },
      { position: 2, driver: "Oscar Piastri", team: "McLaren", metric: "+13.722s", points: 18 },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari", metric: "+15.270s", points: 15 },
    ],
  },
];

const completedWeekendResults: CompletedWeekendResult[] = [
  {
    id: "weekend_aus_2026",
    name: "2026 Australian Grand Prix",
    date_range: "06 - 08 Mar 2026",
    sessions: australiaWeekendSessions,
  },
  {
    id: "weekend_chn_2026",
    name: "2026 Chinese Grand Prix",
    date_range: "13 - 15 Mar 2026",
    sessions: chinaWeekendSessions,
  },
  {
    id: "weekend_jpn_2026",
    name: "2026 Japanese Grand Prix",
    date_range: "27 - 29 Mar 2026",
    sessions: latestWeekendSessions,
  },
];

const calendar: ScheduleRace[] = [
  { round: 1, grand_prix: "Australian Grand Prix", date_range: "06 - 08 Mar 2026", venue: "Albert Park", status: "completed", winner: "George Russell", winner_team: "Mercedes" },
  { round: 2, grand_prix: "Chinese Grand Prix", date_range: "13 - 15 Mar 2026", venue: "Shanghai", status: "completed", winner: "Kimi Antonelli", winner_team: "Mercedes" },
  { round: 3, grand_prix: "Japanese Grand Prix", date_range: "27 - 29 Mar 2026", venue: "Suzuka", status: "completed", winner: "Kimi Antonelli", winner_team: "Mercedes" },
  { round: 4, grand_prix: "Miami Grand Prix", date_range: "01 - 03 May 2026", venue: "Miami International Autodrome", status: "next" },
  { round: 5, grand_prix: "Canadian Grand Prix", date_range: "22 - 24 May 2026", venue: "Circuit Gilles Villeneuve", status: "upcoming" },
  { round: 6, grand_prix: "Monaco Grand Prix", date_range: "05 - 07 Jun 2026", venue: "Monte Carlo", status: "upcoming" },
  { round: 7, grand_prix: "Barcelona-Catalunya Grand Prix", date_range: "12 - 14 Jun 2026", venue: "Barcelona-Catalunya", status: "upcoming" },
  { round: 8, grand_prix: "Austrian Grand Prix", date_range: "26 - 28 Jun 2026", venue: "Red Bull Ring", status: "upcoming" },
  { round: 9, grand_prix: "British Grand Prix", date_range: "03 - 05 Jul 2026", venue: "Silverstone", status: "upcoming" },
  { round: 10, grand_prix: "Belgian Grand Prix", date_range: "17 - 19 Jul 2026", venue: "Spa-Francorchamps", status: "upcoming" },
  { round: 11, grand_prix: "Hungarian Grand Prix", date_range: "24 - 26 Jul 2026", venue: "Hungaroring", status: "upcoming" },
  { round: 12, grand_prix: "Dutch Grand Prix", date_range: "21 - 23 Aug 2026", venue: "Zandvoort", status: "upcoming" },
  { round: 13, grand_prix: "Italian Grand Prix", date_range: "04 - 06 Sep 2026", venue: "Monza", status: "upcoming" },
  { round: 14, grand_prix: "Spanish Grand Prix", date_range: "11 - 13 Sep 2026", venue: "Madrid", status: "upcoming" },
  { round: 15, grand_prix: "Azerbaijan Grand Prix", date_range: "24 - 26 Sep 2026", venue: "Baku City Circuit", status: "upcoming" },
  { round: 16, grand_prix: "Singapore Grand Prix", date_range: "09 - 11 Oct 2026", venue: "Marina Bay", status: "upcoming" },
  { round: 17, grand_prix: "United States Grand Prix", date_range: "23 - 25 Oct 2026", venue: "Circuit of the Americas", status: "upcoming" },
  { round: 18, grand_prix: "Mexico City Grand Prix", date_range: "30 Oct - 01 Nov 2026", venue: "Autodromo Hermanos Rodriguez", status: "upcoming" },
  { round: 19, grand_prix: "Sao Paulo Grand Prix", date_range: "06 - 08 Nov 2026", venue: "Interlagos", status: "upcoming" },
  { round: 20, grand_prix: "Las Vegas Grand Prix", date_range: "19 - 21 Nov 2026", venue: "Las Vegas Strip Circuit", status: "upcoming" },
  { round: 21, grand_prix: "Qatar Grand Prix", date_range: "27 - 29 Nov 2026", venue: "Lusail", status: "upcoming" },
  { round: 22, grand_prix: "Abu Dhabi Grand Prix", date_range: "04 - 06 Dec 2026", venue: "Yas Marina Circuit", status: "upcoming" },
];

const clusters: Cluster[] = [
  {
    id: "cluster_miami_schedule",
    slug: "miami-sprint-weekend",
    title: "Miami is the next event and it returns as a sprint weekend",
    label: "official_update",
    status: "confirmed",
    race_stage: "between_races",
    freshness: "new",
    confidence: 0.98,
    trend: "rising",
    summary: {
      id: "summary_miami_schedule",
      label: "official_update",
      title: "The current phase is between races, with Miami next on a sprint format",
      body: "The official Formula 1 calendar now has Japan complete and Miami next from May 1-3, 2026. The app should treat the current state as a between-races window, not active practice.",
      editorial_status: "approved",
      updated_at: "2026-04-01T17:10:00Z",
    },
    documents: [
      {
        id: "doc_miami_schedule",
        source_id: "source_formula1",
        title: "2026 Miami Grand Prix schedule",
        url: "https://www.formula1.com/en/racing/2026/miami",
        kind: "schedule",
        publish_time: "2026-04-01T17:00:00Z",
        race_stage: "between_races",
        stance: "official",
      },
    ],
    entities: byId(entities, ["circuit_miami"]),
    sources: byId(sources, ["source_formula1"]),
    source_count: 1,
    document_count: 1,
    weekend: {
      id: "weekend_mia_2026",
      name: "2026 Miami Grand Prix",
      stage: "between_races",
    },
  },
  {
    id: "cluster_japan_result",
    slug: "japan-result-reset",
    title: "Japan ended with Antonelli leading the championship",
    label: "race_result",
    status: "confirmed",
    race_stage: "post_race",
    freshness: "settled",
    confidence: 0.99,
    trend: "closed",
    summary: {
      id: "summary_japan_result",
      label: "race_result",
      title: "Antonelli left Suzuka with both the win and the championship lead",
      body: "Japan is now a completed and verified race surface. Antonelli won on March 29, 2026 from Oscar Piastri and Charles Leclerc, moving Mercedes to the top of both championships.",
      editorial_status: "approved",
      updated_at: "2026-03-29T08:10:00Z",
    },
    documents: [
      {
        id: "doc_japan_race_report",
        source_id: "source_formula1",
        title: "Antonelli takes championship lead after victory in Japan",
        url: "https://www.formula1.com/en/latest/article/antonelli-takes-championship-lead-after-surging-to-victory-in-japan-from.4EC4uZc29IUEO2iE5nKpUp/",
        kind: "race_report",
        publish_time: "2026-03-29T07:58:00Z",
        race_stage: "post_race",
        stance: "official",
      },
    ],
    entities: byId(entities, ["driver_antonelli", "driver_piastri", "driver_leclerc", "team_mercedes"]),
    sources: byId(sources, ["source_formula1"]),
    source_count: 1,
    document_count: 1,
    weekend: {
      id: "weekend_jpn_2026",
      name: "2026 Japanese Grand Prix",
      stage: "post_race",
    },
  },
  {
    id: "cluster_mercedes_lead",
    slug: "mercedes-opens-gap",
    title: "Mercedes has turned the first three rounds into a genuine championship gap",
    label: "analysis",
    status: "developing",
    race_stage: "between_races",
    freshness: "live",
    confidence: 0.9,
    trend: "rising",
    summary: {
      id: "summary_mercedes_lead",
      label: "analysis",
      title: "Mercedes has the strongest opening-season signal after three rounds",
      body: "This read is grounded in official standings rather than speculation: Mercedes has taken all three wins and leads Ferrari 135 to 90, while Antonelli and Russell sit first and second in the Drivers' Championship.",
      editorial_status: "approved",
      updated_at: "2026-04-01T18:05:00Z",
    },
    documents: [
      {
        id: "doc_driver_standings",
        source_id: "source_formula1",
        title: "2026 Drivers' Standings",
        url: "https://www.formula1.com/en/results/2026/drivers",
        kind: "standings",
        publish_time: "2026-04-01T18:00:00Z",
        race_stage: "between_races",
        stance: "official",
      },
      {
        id: "doc_team_standings",
        source_id: "source_formula1",
        title: "2026 Teams' Standings",
        url: "https://www.formula1.com/en/results/2026/team",
        kind: "standings",
        publish_time: "2026-04-01T18:00:00Z",
        race_stage: "between_races",
        stance: "official",
      },
    ],
    entities: byId(entities, ["driver_antonelli", "driver_russell", "driver_leclerc", "team_mercedes", "team_ferrari"]),
    sources: byId(sources, ["source_formula1"]),
    source_count: 1,
    document_count: 2,
    weekend: {
      id: "weekend_mia_2026",
      name: "2026 Miami Grand Prix",
      stage: "between_races",
    },
  },
  {
    id: "cluster_miami_prediction",
    slug: "miami-top-three-prediction",
    title: "The current top-three projection for Miami starts with the Mercedes pair",
    label: "prediction",
    status: "watchlist",
    race_stage: "between_races",
    freshness: "live",
    confidence: 0.67,
    trend: "watch",
    summary: {
      id: "summary_miami_prediction",
      label: "prediction",
      title: "Miami projection: Antonelli, Russell, then Leclerc",
      body: "This is explicitly predictive, not official. Based on the current standings, the opening three race results, and Mercedes' pace profile so far, the most defensible early Miami podium call is Antonelli from Russell, with Leclerc as Ferrari's strongest challenger.",
      editorial_status: "review_required",
      updated_at: "2026-04-01T19:45:00Z",
    },
    documents: [
      {
        id: "doc_miami_prediction_basis",
        source_id: "source_the_race",
        title: "Why Miami could reward the strongest all-round car again",
        url: "https://www.the-race.com/formula-1/miami-2026-form-guide",
        kind: "analysis_article",
        publish_time: "2026-04-01T19:30:00Z",
        race_stage: "between_races",
        stance: "analysis",
      },
    ],
    entities: byId(entities, ["driver_antonelli", "driver_russell", "driver_leclerc", "circuit_miami"]),
    sources: byId(sources, ["source_formula1", "source_the_race"]),
    source_count: 2,
    document_count: 1,
    weekend: {
      id: "weekend_mia_2026",
      name: "2026 Miami Grand Prix",
      stage: "between_races",
    },
  },
];

export const dashboardMock: DashboardResponse = {
  weekend: {
    id: "weekend_mia_2026",
    name: "2026 Miami Grand Prix",
    stage: "between_races",
    changes_since_last_race: [
      "Kimi Antonelli leads the Drivers' Championship after winning in Japan on March 29, 2026.",
      "Mercedes leads the Constructors' Championship on 135 points after taking all three race wins so far.",
      "The next event is Miami on May 1-3, 2026, and it is a sprint weekend.",
    ],
    previous_weekend_name: "2026 Japanese Grand Prix",
    date_range: "01 - 03 May 2026",
  },
  hero: {
    eyebrow: "Formula 1 season center",
    title: "2026 championship state",
    subtitle: "Japan finished on March 29, 2026. The next race is the Miami Grand Prix on May 1-3, 2026.",
    stage: "between_races",
    updated_at: "2026-04-01T19:45:00Z",
    signal_score: "Round 3 complete · next Miami Grand Prix",
  },
  what_changed: [
    "Kimi Antonelli leads the Drivers' Championship after winning in Japan on March 29, 2026.",
    "Mercedes leads the Constructors' Championship on 135 points after taking all three race wins so far.",
    "The next event is Miami on May 1-3, 2026, and it is a sprint weekend.",
  ],
  sections: {
    official_updates: [clusters[0]],
    race_results: [clusters[1]],
    analysis: [clusters[2]],
    predictions: [clusters[3]],
  },
  top_clusters: clusters,
  timeline,
  season: {
    year: 2026,
    current_phase: "between_races",
    status_note: "Japan finished on March 29, 2026. The next race is the Miami Grand Prix on May 1-3, 2026.",
    leader_driver: "Kimi Antonelli",
    leader_team: "Mercedes",
    rounds_completed: 3,
    total_rounds: 22,
    next_race_name: "Miami Grand Prix",
    next_race_date_range: "01 - 03 May 2026",
    next_race_sessions: [
      { name: "Practice 1", time_local: "01 May · 09:30 - 10:30 PDT" },
      { name: "Sprint Qualifying", time_local: "01 May · 13:30 - 14:14 PDT" },
      { name: "Sprint", time_local: "02 May · 09:00 - 10:00 PDT" },
      { name: "Qualifying", time_local: "02 May · 13:00 - 14:00 PDT" },
      { name: "Race", time_local: "03 May · 13:00 - 15:00 PDT" },
    ],
  },
  latest_weekend_results: {
    name: "2026 Japanese Grand Prix",
    date_range: "27 - 29 Mar 2026",
    sessions: latestWeekendSessions,
  },
  completed_weekend_results: completedWeekendResults,
  driver_standings: driverStandings,
  constructor_standings: constructorStandings,
  team_cars: teamCars,
  article_feed: articleFeed,
  calendar,
  performance_charts: performanceCharts,
  next_race_prediction: {
    race_name: "Miami Grand Prix",
    date_range: "01 - 03 May 2026",
    weekend_format: "Sprint",
    reason: "Inference from official results and standings: Mercedes has won all three completed races, Antonelli leads the Drivers' standings on 72 points, Russell is second on 63, and Ferrari has been the clearest challenger through Leclerc's consistency.",
    top_three: [
      { position: 1, driver: "Kimi Antonelli", team: "Mercedes" },
      { position: 2, driver: "George Russell", team: "Mercedes" },
      { position: 3, driver: "Charles Leclerc", team: "Ferrari" },
    ],
  },
  sync: {
    source: "seed",
    last_attempt_at: null,
    last_success_at: null,
    status: "idle",
    message: "No OpenF1 sync has run yet.",
  },
  source_rollup: {
    official_count: 2,
    media_count: 1,
    team_count: 1,
    total_sources: 4,
    total_documents: 5,
  },
};

export const predictionAnalyticsMock: PredictionAnalyticsResponse = {
  race: {
    name: "Miami Grand Prix",
    date_range: "01 - 03 May 2026",
    weekend_format: "Sprint",
    venue: "Miami International Autodrome",
    phase: "between_races",
  },
  track: {
    track_type: "Street-style temporary circuit",
    street_circuit_bias: 0.84,
    overtaking_score: 0.78,
    tyre_stress_score: 0.63,
    traction_importance: 0.81,
    track_evolution: 0.74,
    weather_variability: 0.68,
    expected_strategy:
      "Sprint weekend bias with a likely one-stop race and high value on track position after Saturday.",
    tyre_outlook:
      "Rear-limited overheating risk rewards smooth traction and disciplined tyre warm-up.",
    notes:
      "Miami-style profiles reward confidence over traction zones, efficient straight-line speed, and tyre preservation in heat.",
  },
  model: {
    name: "Hybrid F1 Winner Model",
    version: "0.1.0",
    overview:
      "The model blends engineered motorsport priors, an in-app calibration layer, and a historical classifier trained on Ergast-compatible race and qualifying data when that stack is available.",
    target: "Predict the most likely winner of the next Formula 1 race weekend.",
    training: {
      completed_races: 24,
      observations: 475,
      positive_examples: 20,
      blend: "34% domain feature prior + 18% in-app calibration + 48% historical classifier",
    },
    confidence: "developing",
    notes: [
      "Inference, not an official result. The current repo contributes live season context while the optional historical stack lifts sample size.",
      "Historical training uses bulk Ergast-compatible race and qualifying pulls, with FastF1 schedule metadata available for event context.",
      "Tyre and strategy signals are modeled as expected weekend conditions rather than official team declarations.",
    ],
  },
  contenders: [
    {
      rank: 1,
      driver: "Kimi Antonelli",
      team: "Mercedes",
      win_probability: 0.287,
      podium_probability: 0.694,
      model_score: 0.824,
      confidence: "high",
      outlook:
        "Kimi Antonelli arrives as a strong favorite because current form and street-circuit fit are both elite.",
      evidence: [
        "2 season wins and 3 podiums so far.",
        "Car formula: 93.0% for the current Mercedes package.",
        "Track fit: 86.0% against a street-style temporary circuit profile.",
        "Expected strategy: 84.0% under the projected race plan.",
      ],
      features: [
        { key: "championship_form", label: "Championship form", value: 0.93, display_value: "93.0%", impact: "Current points, ranking, and recent momentum entering the weekend." },
        { key: "constructor_strength", label: "Car formula", value: 0.93, display_value: "93.0%", impact: "Current constructor package strength, pit crew sharpness, and car platform quality." },
        { key: "season_wins", label: "Season wins", value: 0.67, display_value: "66.7%", impact: "Win conversion so far this season." },
        { key: "podium_rate", label: "Podium rate", value: 1, display_value: "100.0%", impact: "Ability to stay in the fight across multiple race conditions." },
        { key: "qualifying_sharpness", label: "Qualifying pace", value: 0.95, display_value: "95.0%", impact: "Average grid strength and one-lap execution." },
        { key: "recent_race_form", label: "Recent race form", value: 0.94, display_value: "94.0%", impact: "Last-race finishing trend and consistency score." },
        { key: "career_wins", label: "Career wins", value: 0.03, display_value: "2.7%", impact: "Senior-category race-winning experience." },
        { key: "junior_provenance", label: "Junior leagues", value: 0.7, display_value: "70.0%", impact: "Formula 2, Formula 3, and junior series record." },
        { key: "experience_depth", label: "Experience", value: 0.05, display_value: "5.0%", impact: "Seasons at top level and high-pressure decision-making." },
        { key: "track_fit", label: "Track fit", value: 0.86, display_value: "86.0%", impact: "Street-circuit and layout suitability for the upcoming venue." },
        { key: "tyre_management_fit", label: "Tyre management", value: 0.84, display_value: "84.0%", impact: "Ability to protect the tyre life profile expected this weekend." },
        { key: "strategy_alignment", label: "Expected strategy", value: 0.84, display_value: "84.0%", impact: "Fit for the likely race plan and sprint-weekend setup compromise." },
        { key: "reliability", label: "Reliability", value: 0.9, display_value: "90.0%", impact: "Mechanical finish probability and operational cleanliness." },
        { key: "weather_adaptability", label: "Weather adaptability", value: 0.76, display_value: "76.0%", impact: "Response to changing grip, heat, and wet-track disruption." },
      ],
    },
    {
      rank: 2,
      driver: "George Russell",
      team: "Mercedes",
      win_probability: 0.239,
      podium_probability: 0.642,
      model_score: 0.795,
      confidence: "medium",
      outlook:
        "George Russell looks dangerous if Mercedes locks in track position early on this sprint-style weekend.",
      evidence: [
        "1 season win and 2 podiums so far.",
        "Car formula: 93.0% for the current Mercedes package.",
        "Track fit: 82.0% against a street-style temporary circuit profile.",
        "Expected strategy: 83.0% under the projected race plan.",
      ],
      features: [
        { key: "championship_form", label: "Championship form", value: 0.88, display_value: "88.0%", impact: "Current points, ranking, and recent momentum entering the weekend." },
        { key: "constructor_strength", label: "Car formula", value: 0.93, display_value: "93.0%", impact: "Current constructor package strength, pit crew sharpness, and car platform quality." },
        { key: "season_wins", label: "Season wins", value: 0.33, display_value: "33.3%", impact: "Win conversion so far this season." },
        { key: "podium_rate", label: "Podium rate", value: 0.67, display_value: "66.7%", impact: "Ability to stay in the fight across multiple race conditions." },
        { key: "qualifying_sharpness", label: "Qualifying pace", value: 0.9, display_value: "90.0%", impact: "Average grid strength and one-lap execution." },
        { key: "recent_race_form", label: "Recent race form", value: 0.84, display_value: "84.0%", impact: "Last-race finishing trend and consistency score." },
        { key: "career_wins", label: "Career wins", value: 0.05, display_value: "5.5%", impact: "Senior-category race-winning experience." },
        { key: "junior_provenance", label: "Junior leagues", value: 0.86, display_value: "86.0%", impact: "Formula 2, Formula 3, and junior series record." },
        { key: "experience_depth", label: "Experience", value: 0.4, display_value: "40.0%", impact: "Seasons at top level and high-pressure decision-making." },
        { key: "track_fit", label: "Track fit", value: 0.82, display_value: "82.0%", impact: "Street-circuit and layout suitability for the upcoming venue." },
        { key: "tyre_management_fit", label: "Tyre management", value: 0.83, display_value: "83.0%", impact: "Ability to protect the tyre life profile expected this weekend." },
        { key: "strategy_alignment", label: "Expected strategy", value: 0.83, display_value: "83.0%", impact: "Fit for the likely race plan and sprint-weekend setup compromise." },
        { key: "reliability", label: "Reliability", value: 0.88, display_value: "88.0%", impact: "Mechanical finish probability and operational cleanliness." },
        { key: "weather_adaptability", label: "Weather adaptability", value: 0.82, display_value: "82.0%", impact: "Response to changing grip, heat, and wet-track disruption." },
      ],
    },
    {
      rank: 3,
      driver: "Charles Leclerc",
      team: "Ferrari",
      win_probability: 0.181,
      podium_probability: 0.556,
      model_score: 0.744,
      confidence: "medium",
      outlook:
        "Charles Leclerc looks dangerous if Ferrari locks in track position early on this sprint-style weekend.",
      evidence: [
        "0 season wins and 3 podiums so far.",
        "Car formula: 86.0% for the current Ferrari package.",
        "Track fit: 87.0% against a street-style temporary circuit profile.",
        "Expected strategy: 79.0% under the projected race plan.",
      ],
      features: [
        { key: "championship_form", label: "Championship form", value: 0.76, display_value: "76.0%", impact: "Current points, ranking, and recent momentum entering the weekend." },
        { key: "constructor_strength", label: "Car formula", value: 0.86, display_value: "86.0%", impact: "Current constructor package strength, pit crew sharpness, and car platform quality." },
        { key: "season_wins", label: "Season wins", value: 0, display_value: "0.0%", impact: "Win conversion so far this season." },
        { key: "podium_rate", label: "Podium rate", value: 1, display_value: "100.0%", impact: "Ability to stay in the fight across multiple race conditions." },
        { key: "qualifying_sharpness", label: "Qualifying pace", value: 0.84, display_value: "84.0%", impact: "Average grid strength and one-lap execution." },
        { key: "recent_race_form", label: "Recent race form", value: 0.82, display_value: "82.0%", impact: "Last-race finishing trend and consistency score." },
        { key: "career_wins", label: "Career wins", value: 0.08, display_value: "8.2%", impact: "Senior-category race-winning experience." },
        { key: "junior_provenance", label: "Junior leagues", value: 0.59, display_value: "59.0%", impact: "Formula 2, Formula 3, and junior series record." },
        { key: "experience_depth", label: "Experience", value: 0.45, display_value: "45.0%", impact: "Seasons at top level and high-pressure decision-making." },
        { key: "track_fit", label: "Track fit", value: 0.87, display_value: "87.0%", impact: "Street-circuit and layout suitability for the upcoming venue." },
        { key: "tyre_management_fit", label: "Tyre management", value: 0.79, display_value: "79.0%", impact: "Ability to protect the tyre life profile expected this weekend." },
        { key: "strategy_alignment", label: "Expected strategy", value: 0.79, display_value: "79.0%", impact: "Fit for the likely race plan and sprint-weekend setup compromise." },
        { key: "reliability", label: "Reliability", value: 0.84, display_value: "84.0%", impact: "Mechanical finish probability and operational cleanliness." },
        { key: "weather_adaptability", label: "Weather adaptability", value: 0.72, display_value: "72.0%", impact: "Response to changing grip, heat, and wet-track disruption." },
      ],
    },
    {
      rank: 4,
      driver: "Lewis Hamilton",
      team: "Ferrari",
      win_probability: 0.112,
      podium_probability: 0.418,
      model_score: 0.688,
      confidence: "watch",
      outlook:
        "Lewis Hamilton profiles as a strategy threat if the race opens into an undercut or safety-car window.",
      evidence: [
        "0 season wins and 1 podium so far.",
        "Car formula: 86.0% for the current Ferrari package.",
        "Track fit: 84.0% against a street-style temporary circuit profile.",
        "Expected strategy: 82.0% under the projected race plan.",
      ],
      features: [],
    },
    {
      rank: 5,
      driver: "Lando Norris",
      team: "McLaren",
      win_probability: 0.085,
      podium_probability: 0.337,
      model_score: 0.652,
      confidence: "watch",
      outlook:
        "Lando Norris needs a clean qualifying and stable tyre life to convert this profile into a win chance.",
      evidence: [
        "0 season wins and 0 podiums so far.",
        "Car formula: 80.0% for the current McLaren package.",
        "Track fit: 80.0% against a street-style temporary circuit profile.",
        "Expected strategy: 80.0% under the projected race plan.",
      ],
      features: [],
    },
  ],
  feature_importance: [
    { label: "Championship form", value: 0.97, description: "Current points, ranking, and recent momentum entering the weekend." },
    { label: "Car formula", value: 0.94, description: "Current constructor package strength, pit crew sharpness, and car platform quality." },
    { label: "Qualifying pace", value: 0.9, description: "Average grid strength and one-lap execution." },
    { label: "Track fit", value: 0.88, description: "Street-circuit and layout suitability for the upcoming venue." },
    { label: "Tyre management", value: 0.84, description: "Ability to protect the tyre life profile expected this weekend." },
    { label: "Expected strategy", value: 0.82, description: "Fit for the likely race plan and sprint-weekend setup compromise." },
  ],
  constructor_outlook: [
    { team: "Mercedes", car_formula: "Balanced high-downforce platform", power_score: 0.93, qualifying_score: 0.92, tyre_score: 0.86, reliability: 0.9 },
    { team: "Ferrari", car_formula: "Front-end sharp qualifying package", power_score: 0.87, qualifying_score: 0.91, tyre_score: 0.79, reliability: 0.85 },
    { team: "McLaren", car_formula: "High-speed aero efficiency package", power_score: 0.86, qualifying_score: 0.87, tyre_score: 0.84, reliability: 0.84 },
    { team: "Red Bull Racing", car_formula: "Peak-downforce aggressive rotation package", power_score: 0.84, qualifying_score: 0.88, tyre_score: 0.85, reliability: 0.8 },
  ],
  scenario_matrix: [
    {
      title: "Front-row lockout",
      description:
        "If Kimi Antonelli starts on the first row, the current model expects clean-air advantage to matter more than strategy variance.",
      effect: "Boosts the favorite and suppresses midfield upset paths.",
    },
    {
      title: "High-degradation race",
      description:
        "If Miami heat pushes tyre wear higher than expected, the model shifts toward drivers with stronger tyre-management scores such as George Russell.",
      effect: "Strengthens strategy-first contenders and increases podium volatility.",
    },
    {
      title: "Safety-car reshuffle",
      description:
        "With overtaking weighted heavily in the track model, a late neutralization can materially reopen the race even after the first stop cycle.",
      effect: "Raises upset probability and compresses the top-six outcome spread.",
    },
  ],
  source_stack: [
    {
      label: "OpenF1 live season cache",
      kind: "data",
      role: "Current season standings, session results, pace traces, and live weekend context already wired into this codebase.",
      url: "https://openf1.org/docs",
    },
    {
      label: "FastF1",
      kind: "data",
      role: "Telemetry-compatible data source for session, tyre, and lap-level enrichment when a deeper research pipeline is added.",
      url: "https://docs.fastf1.dev/getting_started/basics.html",
    },
    {
      label: "Ergast Developer API",
      kind: "data",
      role: "Historical archive reference for long-run driver, team, and circuit priors from 1950 onward.",
      url: "http://ergast.com/mrd/",
    },
    {
      label: "scikit-learn workflow",
      kind: "modeling",
      role: "Reference workflow for gradient-boosted and classical classification approaches described in the methodology panel.",
      url: "https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html",
    },
    {
      label: "XGBoost classifier",
      kind: "modeling",
      role: "Reference tree-boosting option for a future production training job once more labeled race data is wired in.",
      url: "https://xgboost.readthedocs.io/en/stable/python/python_api.html#xgboost.XGBClassifier",
    },
    {
      label: "F1 Race Replay",
      kind: "inspiration",
      role: "Telemetry and tyre visualization reference for future simulation overlays and race-shape replays.",
      url: "https://github.com/IAmTomShaw/f1-race-replay",
    },
    {
      label: "F1 race prediction simulator",
      kind: "inspiration",
      role: "Multi-factor simulation reference covering driver skill, car quality, track characteristics, and weather.",
      url: "https://github.com/mehmetkahya0/f1-race-prediction",
    },
    {
      label: "SQL and Python team-performance article",
      kind: "analysis",
      role: "Warehouse-style aggregation reference for team trend tables and longitudinal performance views.",
      url: "https://medium.com/@themathlab/analyzing-formula-1-team-performance-with-sql-and-python-1e30f1e154b9",
    },
  ],
};

export const clustersMock = clusters;
export const clusterMapMock = Object.fromEntries(clusters.map((cluster) => [cluster.id, cluster]));
export const sourcesMock = sources;
export const entitiesMock = entities;
